# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Builds the iOS app"
  lane :build_app do
    gym(                      # gym is the built-in tool for building iOS apps
      workspace: "FastlaneJenkinsTest.xcworkspace",  # Replace with your workspace name
      scheme: "FastlaneJenkinsTest",      # Replace with your scheme name
      configuration: "Release", # Use "Debug" if needed
      clean: true,            # Cleans the build folder before building
      export_method: "app-store" # Change to "ad-hoc" or "development" if needed
    )
  end
end

