# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

default_platform(:ios)

platform :ios do
  desc "Builds the iOS app"
  lane :build_app do
    gym(                      
      workspace: "FastlaneJenkinsTest.xcworkspace",
      scheme: "FastlaneJenkinsTest",
      configuration: "Release",
      clean: true,
      export_method: "app-store",
      output_directory: "/Users/ft42/Documents/Demo Projects",  # ✅ Custom output path
      output_name: "FastlaneJenkinsTest.ipa"  # ✅ Custom IPA file name
    )
  end
end


